# Client ID (unique identifier for this client)
clientID: "web-server"

# Server address
serverAddress: "tunnel.example.com:8443"

# Access key for authentication
accessKey: "secret-key-1"

# TLS configuration
useTLS: true
verifyCert: true

# Optional CA certificate file for custom CA trust
# caFile: "/path/to/ca.pem"

# Reconnection settings
maxReconnectAttempts: 10
reconnectDelay: 5
